import type { Profile, Match, User, Interest, Billing } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "john@example.com",
    name: "John Doe",
    avatar: "/professional-man.png",
    subscription: {
      plan: "premium",
      status: "active",
      expiresAt: "2024-12-31T23:59:59Z",
    },
    createdAt: "2024-01-15T10:00:00Z",
  },
]

export const mockProfiles: Profile[] = [
  {
    id: "1",
    userId: "1",
    name: "Sarah Chen",
    avatar: "/professional-woman-smiling.png",
    dob: "1992-05-15",
    gender: "Female",
    streamUserId: "stream_1",
    income: 85000,
    age: 31,
    city: "San Francisco",
    state: "California",
    country: "USA",
    religion: "Buddhist",
    education: "Masters in Computer Science",
    profession: "Software Engineer",
    purpose: {
      domain: "Technology & Innovation",
      archetype: "The Creator",
      modality: "Collaborative",
      narrative: "Building meaningful technology that connects people and solves real-world problems",
    },
    isNew: false,
    createdAt: "2024-01-20T10:00:00Z",
    interests: ["Technology", "Meditation", "Hiking", "Cooking"],
    personality: "INTJ",
    maritalStatus: "Never Married",
    lookingFor: "Long-term relationship",
    language: "English, Mandarin",
    height: 165,
    weight: 58,
    smoke: "Never",
    alcohol: "Occasionally",
    drugs: "Never",
    politics: ["Progressive", "Environmental"],
    isVerified: true,
    isDeleted: false,
    isActive: true,
  },
  {
    id: "2",
    userId: "2",
    name: "Michael Rodriguez",
    avatar: "/professional-engineer.png",
    dob: "1988-09-22",
    gender: "Male",
    streamUserId: "stream_2",
    income: 95000,
    age: 35,
    city: "Austin",
    state: "Texas",
    country: "USA",
    religion: "Catholic",
    education: "PhD in Mechanical Engineering",
    profession: "Research Engineer",
    purpose: {
      domain: "Sustainable Energy",
      archetype: "The Innovator",
      modality: "Analytical",
      narrative: "Developing clean energy solutions for a sustainable future",
    },
    isNew: true,
    createdAt: "2024-02-01T10:00:00Z",
    interests: ["Renewable Energy", "Rock Climbing", "Photography", "Travel"],
    personality: "ENTP",
    maritalStatus: "Divorced",
    lookingFor: "Serious relationship",
    language: "English, Spanish",
    height: 178,
    weight: 75,
    smoke: "Never",
    alcohol: "Socially",
    drugs: "Never",
    politics: ["Moderate", "Environmental"],
    isVerified: true,
    isDeleted: false,
    isActive: true,
  },
  {
    id: "3",
    userId: "3",
    name: "Priya Sharma",
    avatar: "/indian-woman-doctor.png",
    dob: "1990-12-08",
    gender: "Female",
    streamUserId: "stream_3",
    income: 120000,
    age: 33,
    city: "New York",
    state: "New York",
    country: "USA",
    religion: "Hindu",
    education: "MD in Cardiology",
    profession: "Cardiologist",
    purpose: {
      domain: "Healthcare & Wellness",
      archetype: "The Healer",
      modality: "Empathetic",
      narrative: "Dedicated to healing hearts and improving cardiovascular health outcomes",
    },
    isNew: false,
    createdAt: "2024-01-10T10:00:00Z",
    interests: ["Medicine", "Yoga", "Classical Music", "Volunteering"],
    personality: "ISFJ",
    maritalStatus: "Never Married",
    lookingFor: "Marriage",
    language: "English, Hindi, Tamil",
    height: 160,
    weight: 52,
    smoke: "Never",
    alcohol: "Never",
    drugs: "Never",
    politics: ["Liberal", "Healthcare Reform"],
    isVerified: true,
    isDeleted: false,
    isActive: true,
  },
]

export const mockMatches: Match[] = [
  {
    id: "1",
    profile: mockProfiles[0],
    compatibilityScore: 92,
    purposeAlignment: 88,
    narrative: "Both share a passion for technology and innovation, with complementary approaches to problem-solving.",
    matchedAt: "2024-02-15T10:00:00Z",
    status: "pending",
  },
  {
    id: "2",
    profile: mockProfiles[1],
    compatibilityScore: 85,
    purposeAlignment: 82,
    narrative: "Strong alignment in environmental values and commitment to sustainable solutions.",
    matchedAt: "2024-02-14T10:00:00Z",
    status: "liked",
  },
  {
    id: "3",
    profile: mockProfiles[2],
    compatibilityScore: 78,
    purposeAlignment: 75,
    narrative: "Shared dedication to helping others and making a positive impact in their respective fields.",
    matchedAt: "2024-02-13T10:00:00Z",
    status: "mutual",
  },
]

export const mockInterests: Interest[] = [
  {
    id: "1",
    fromUserId: "2",
    toUserId: "1",
    type: "like",
    createdAt: "2024-02-14T15:30:00Z",
    profile: mockProfiles[1],
  },
  {
    id: "2",
    fromUserId: "3",
    toUserId: "1",
    type: "super_like",
    createdAt: "2024-02-13T12:00:00Z",
    profile: mockProfiles[2],
  },
]

export const mockBilling: Billing = {
  id: "1",
  userId: "1",
  plan: "premium",
  amount: 29.99,
  currency: "USD",
  status: "active",
  currentPeriodStart: "2024-02-01T00:00:00Z",
  currentPeriodEnd: "2024-03-01T00:00:00Z",
  cancelAtPeriodEnd: false,
}
