export enum Role {
  USER = "USER",
  ADMIN = "ADMIN",
}

export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
}

export enum Religion {
  ISLAM = "ISLAM",
  CHRISTIANITY = "CHRISTIANITY",
  HINDUISM = "HINDUISM",
  BUDDHISM = "BUDDHISM",
  JUDAISM = "JUDAISM",
  ATHEISM = "ATHEISM",
  OTHER = "OTHER",
}

export enum Education {
  NONE = "NONE",
  PRIMARY = "PRIMARY",
  SECONDARY = "SECONDARY",
  HIGH_SCHOOL = "HIGH_SCHOOL",
  BACHELORS = "BACHELORS",
  MASTERS = "MASTERS",
  PHD = "PHD",
  SELF_TAUGHT = "SELF_TAUGHT",
  OTHER = "OTHER",
}

export enum Profession {
  STUDENT = "STUDENT",
  ENGINEERING = "ENGINEERING",
  SOFTWARE_DEVELOPMENT = "SOFTWARE_DEVELOPMENT",
  DATA_SCIENCE = "DATA_SCIENCE",
  ARTIFICIAL_INTELLIGENCE = "ARTIFICIAL_INTELLIGENCE",
  MEDICINE = "MEDICINE",
  DENTISTRY = "DENTISTRY",
  NURSING = "NURSING",
  EDUCATION = "EDUCATION",
  BUSINESS = "BUSINESS",
  ENTREPRENEUR = "ENTREPRENEUR",
  FINANCE = "FINANCE",
  MARKETING = "MARKETING",
  SALES = "SALES",
  LAW = "LAW",
  GOVERNMENT = "GOVERNMENT",
  PUBLIC_SERVICE = "PUBLIC_SERVICE",
  DESIGN = "DESIGN",
  WRITING = "WRITING",
  JOURNALISM = "JOURNALISM",
  ARTS = "ARTS",
  FILM = "FILM",
  MUSIC = "MUSIC",
  SPORTS = "SPORTS",
  AGRICULTURE = "AGRICULTURE",
  ARCHITECTURE = "ARCHITECTURE",
  PSYCHOLOGY = "PSYCHOLOGY",
  SOCIAL_WORK = "SOCIAL_WORK",
  FREELANCER = "FREELANCER",
  UNEMPLOYED = "UNEMPLOYED",
  HOMEMAKER = "HOMEMAKER",
  OTHER = "OTHER",
}

export enum PurposeDomain {
  SOCIAL = "SOCIAL",
  ENVIRONMENTAL = "ENVIRONMENTAL",
  TECHNOLOGICAL = "TECHNOLOGICAL",
  EDUCATIONAL = "EDUCATIONAL",
  RELIGIOUS = "RELIGIOUS",
  PERSONAL = "PERSONAL",
}

export enum PurposeArchetype {
  LEADER = "LEADER",
  CREATOR = "CREATOR",
  HEALER = "HEALER",
  EXPLORER = "EXPLORER",
  ADVOCATE = "ADVOCATE",
  VISIONARY = "VISIONARY",
}

export enum PurposeModality {
  INDIVIDUAL = "INDIVIDUAL",
  COMMUNITY = "COMMUNITY",
  GLOBAL = "GLOBAL",
}

export enum Interest {
  SPORTS = "SPORTS",
  MUSIC = "MUSIC",
  TRAVEL = "TRAVEL",
  READING = "READING",
  COOKING = "COOKING",
  ART = "ART",
  TECHNOLOGY = "TECHNOLOGY",
  OTHER = "OTHER",
}

export enum Personality {
  INTROVERT = "INTROVERT",
  EXTROVERT = "EXTROVERT",
  AMBIVERT = "AMBIVERT",
}

export enum MaritalStatus {
  SINGLE = "SINGLE",
  MARRIED = "MARRIED",
  DIVORCED = "DIVORCED",
  WIDOWED = "WIDOWED",
}

export enum LookingFor {
  SINGLE = "SINGLE",
  MARRIED = "MARRIED",
  DIVORCED = "DIVORCED",
  WIDOWED = "WIDOWED",
}

export enum Language {
  ENGLISH = "ENGLISH",
  URDU = "URDU",
  ARABIC = "ARABIC",
  HINDI = "HINDI",
  FRENCH = "FRENCH",
  GERMAN = "GERMAN",
  PUNJABI = "PUNJABI",
  TURKISH = "TURKISH",
  PERSIAN = "PERSIAN",
  OTHER = "OTHER",
}

export enum Smoke {
  YES = "YES",
  NO = "NO",
  OCCASIONALLY = "OCCASIONALLY",
}

export enum Alcohol {
  YES = "YES",
  NO = "NO",
  OCCASIONALLY = "OCCASIONALLY",
}

export enum Drugs {
  YES = "YES",
  NO = "NO",
  OCCASIONALLY = "OCCASIONALLY",
}

export enum Politics {
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  CENTER = "CENTER",
  LIBERTARIAN = "LIBERTARIAN",
  FUNDAMENTALIST = "FUNDAMENTALIST",
  CONSERVATIVE = "CONSERVATIVE",
  OTHER = "OTHER",
}

export enum PhotoStatus {
  ACTIVE = "ACTIVE",
  PENDING = "PENDING",
  DELETED = "DELETED",
}

export enum MatchStatus {
  PENDING = "PENDING",
  INTERESTED = "INTERESTED",
  MATCHED = "MATCHED",
  REJECTED = "REJECTED",
  BLOCKED = "BLOCKED",
}

export enum Plan {
  FREE = "FREE",
  BASIC = "BASIC",
  PREMIUM = "PREMIUM",
  ENTERPRISE = "ENTERPRISE",
}

export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  CANCELED = "CANCELED",
  PAUSED = "PAUSED",
}

export enum PaymentMethod {
  CARD = "CARD",
  PAYPAL = "PAYPAL",
  STRIPE = "STRIPE",
  BANK_TRANSFER = "BANK_TRANSFER",
}

export enum TransactionStatus {
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}
